import { combineReducers } from 'redux';

export const CHANGE_USER_INFO = 'CHANGE_USER_INFO';

export const LOAD_TWEETS = 'LOAD_TWEETS';

export const CHANGE_FLAG_PAGE = "CHANGE_FLAG_PAGE";

export const CHANGE_FLAG_ME = "CHANGE_FLAG_ME";

export const UPDATE_TWEETS_USER = "UPDATE_TWEETS_USER";

export const UPDATE_TWEETS_HOME = "UPDATE_TWEETS_HOME";

export const LOADMORE_TWEETS_HOME = "LOADMORE_TWEETS_HOME"

export const LOAD_FOLLOWING = "LOAD_FOLLOWING";

export const LOAD_FOLLOWER = "LOAD_FOLLOWER";

export const LOADMORE_TWEETS_USER = "LOADMORE_TWEETS_USER";

export const INCREASE_SEQUENCE = "INCREASE_SEQUENCE";

export const CHANGE_NAME = "CHANGE_NAME";

export const ADD_NEW_TWEET_HOME = "ADD_NEW_TWEET_HOME";

export const UPDATE_HISTORICAL_TRANSACTION = "UPDATE_HISTORICAL_TRANSACTION";

export const LOADMORE_HISTORICAL_TRANSACTION = "LOADMORE_HISTORICAL_TRANSACTION";

export const UPDATE_AVATAR_USER = "UPDATE_AVATAR_USER"